language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r .travis/requirements.txt
# command to run tests
script: python .travis/main.py

deploy:
  provider: netlify
  site: $NETLIFY_SITE
  auth: $NETLIFY_AUTH
  dir: .
  edge: true # opt in to dpl v2
  prod: true